# Generated by Django 5.2.12 on 2026-04-26 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='菜单名称')),
                ('url', models.CharField(max_length=200, verbose_name='URL')),
                ('icon', models.CharField(blank=True, default='', max_length=50, verbose_name='图标')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'db_table': 'main_menu',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='MenuGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '菜单权限',
                'verbose_name_plural': '菜单权限',
                'db_table': 'main_menugroup',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='组名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='组代码')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户组',
                'verbose_name_plural': '用户组',
                'db_table': 'main_usergroup',
            },
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '用户扩展信息', 'verbose_name_plural': '用户扩展信息'},
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='main_userpr_phone_2276ba_idx',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='main_userpr_real_na_db1c17_idx',
        ),
        migrations.AddField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.menu', verbose_name='父菜单'),
        ),
        migrations.AddField(
            model_name='menugroup',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.menu'),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='menus',
            field=models.ManyToManyField(through='main.MenuGroup', to='main.menu', verbose_name='菜单权限'),
        ),
        migrations.AddField(
            model_name='menugroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usergroup'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.usergroup', verbose_name='用户组'),
        ),
        migrations.AlterUniqueTogether(
            name='menugroup',
            unique_together={('menu', 'group')},
        ),
    ]
