# Generated by Django 5.2.12 on 2026-05-01 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_menu_menugroup_usergroup_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='yhbh',
            field=models.IntegerField(blank=True, help_text='对应USERS表的YHBH', null=True, verbose_name='档案系统用户编号'),
        ),
    ]
